import chromadb
from chromadb.utils import embedding_functions
from chromadb.config import Settings

client = chromadb.Client(
    Settings(
        persist_directory=".chroma", 
        anonymized_telemetry=False
    )
)

collection = client.get_or_create_collection(
    name="book_versions",
    embedding_function=embedding_functions.DefaultEmbeddingFunction()
)


versions = {
    "original": "This is the original scraped chapter.",
    "ai_writer_v1": "This version was generated by the AI writer.",
    "ai_reviewer_v1": "This version was refined by the AI reviewer.",
    "human_edit_v1": "This version was edited by a human - first iteration.",
    "human_edit_v2": "This version was edited by a human - second iteration."
}


for tag, content in versions.items():
    collection.add(documents=[content], ids=[tag])

print("✅ Inserted versions into ChromaDB.")
print("📚 Stored IDs:", collection.get()["ids"])
